const WINDOW_WIDTH = window.innerWidth
const WINDOW_HEIGHT = window.innerHeight

const SCENE_POSITION_X = 100
const SCENE_POSITION_Y = 100

const SCENE_WIDTH = WINDOW_WIDTH - SCENE_POSITION_X - (260 + 50)
const SCENE_HEIGHT = WINDOW_HEIGHT - SCENE_POSITION_Y - 50

const HTML_ID_PREFIX = 'app-el-'
const CANVAS_CONTEXT_TYPE = '2d'